In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4])

In [4]:
np.array([-32], dtype=np.int8)

array([-32], dtype=int8)

In [5]:
np.uint8(10) / np.uint8(5)

np.float64(2.0)

In [6]:
np.arange(2,3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [7]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [8]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2, 3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
np.diag(np.random.default_rng(42).random((3,4)))

array([0.77395605, 0.97562235, 0.37079802])

In [11]:
np.random.default_rng(42).random((3,4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [12]:
np.indices((4,5,3))

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]],


       [[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]]],


       [[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]

## works on ndarrays

In [13]:
a2 = np.array([1,2,3,4])

In [14]:
b = a2[:3]

In [15]:
b[1]=4
b

array([1, 4, 3])

In [16]:
a2

array([1, 4, 3, 4])

In [17]:
b2 = a2
b2[2]=11
a2

array([ 1,  4, 11,  4])

In [18]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [19]:
aa = [[1],2,3,4,5]

In [20]:
aa[1,2]

TypeError: list indices must be integers or slices, not tuple

In [21]:
a3 = np.arange(10)
a3[2]


np.int64(2)

In [22]:
a3 = a3.reshape((2,5))
a3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
a3 = a3.reshape((1,10))
a3

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
a3[0,3:6:1]


array([3, 4, 5])

In [25]:
xx = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
xx[1:7:3]

array([1, 4])

## advanced indexing

In [27]:
x = np.arange(10, 1, -1)

In [28]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [29]:
a = np.random.randn(5,3)

In [30]:
a

array([[ 2.06911114, -0.23619693,  0.21095246],
       [ 0.23308742, -0.18717216,  0.32830311],
       [-0.02470477, -1.80652882, -0.56327682],
       [-0.06273571, -0.3545101 , -1.10232209],
       [ 1.20211453,  1.04967926, -0.14721082]])

In [31]:
a[np.array([2,4])]

array([[-0.02470477, -1.80652882, -0.56327682],
       [ 1.20211453,  1.04967926, -0.14721082]])

In [32]:
np.array(["hello", "worl"], dtype='S7').tobytes()

b'hello\x00\x00worl\x00\x00\x00'

In [33]:
a = np.arange(20).reshape(5,4)
a1 = np.arange(5).reshape(5,1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
a*a1

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22],
       [36, 39, 42, 45],
       [64, 68, 72, 76]])

In [35]:
a1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [36]:
a*np.array([100,100,100,100])

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100],
       [1200, 1300, 1400, 1500],
       [1600, 1700, 1800, 1900]])

In [37]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
diff

array([[ -9.,  15.],
       [ 21.,   5.],
       [-66., -33.],
       [-54., -15.]])

In [43]:
a = np.arange(15)
b = a.reshape(3,5)
b[1,2] = -3
a

array([ 0,  1,  2,  3,  4,  5,  6, -3,  8,  9, 10, 11, 12, 13, 14])

In [44]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, -3,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
b.base

array([ 0,  1,  2,  3,  4,  5,  6, -3,  8,  9, 10, 11, 12, 13, 14])