In [2]:
import torch
import numpy as np

In [5]:
data = [[1,2], [3,4]]
a1 = np.array(data)
a2 = torch.tensor(data)

In [6]:
a1

array([[1, 2],
       [3, 4]])

In [9]:
a2

tensor([[1, 2],
        [3, 4]])

In [10]:
a3 = torch.from_numpy(a1)

In [14]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [18]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
a = torch.rand(4,5)
a

tensor([[0.5182, 0.0383, 0.0415, 0.8800, 0.8774],
        [0.7784, 0.2038, 0.8236, 0.3053, 0.7118],
        [0.7435, 0.1169, 0.3448, 0.8283, 0.7120],
        [0.3280, 0.9263, 0.1906, 0.6199, 0.7368]])

In [40]:
a

tensor([[0.5182, 0.0383, 0.0415, 0.8800, 0.8774],
        [0.7784, 0.2038, 0.8236, 0.3053, 0.7118],
        [0.7435, 0.1169, 0.3448, 0.8283, 0.7120],
        [0.3280, 0.9263, 0.1906, 0.6199, 0.7368]])

In [44]:
t1 = torch.ones(4,5)
t1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [53]:
t2 = torch.rand(4,2)
t2

tensor([[0.1198, 0.0111],
        [0.4572, 0.7395],
        [0.9967, 0.1726],
        [0.4028, 0.0545]])

In [54]:
catt = torch.hstack((t1, t2))
catt

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.1198, 0.0111],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.4572, 0.7395],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.9967, 0.1726],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.4028, 0.0545]])

In [63]:
def tensor_like(tnsr):
    return torch.rand(tnsr.shape)


tensor_like(catt)

tensor([[0.7740, 0.6108, 0.3377, 0.5359, 0.6735, 0.3768, 0.9579],
        [0.7168, 0.0579, 0.2984, 0.1884, 0.0027, 0.9021, 0.5821],
        [0.1551, 0.0706, 0.6130, 0.8770, 0.6813, 0.4566, 0.0812],
        [0.8251, 0.2654, 0.5809, 0.2404, 0.2199, 0.5887, 0.9953]])

In [72]:
o = torch.tensor(2.5)

In [73]:
o.item()

2.5

In [76]:
t2.numpy().dtype

dtype('float32')

In [9]:
values, indx = torch.sort(torch.tensor([1,11,22,3,44]))

In [10]:
indx

tensor([0, 3, 1, 2, 4])

In [11]:
values

tensor([ 1,  3, 11, 22, 44])

# t.split

In [36]:
import torch
q = torch.randn(32,16)
q

tensor([[ 1.2276e+00, -6.4186e-01,  3.2041e-01, -9.1565e-02,  7.9403e-01,
         -7.4451e-01, -6.6837e-01, -7.9203e-01,  2.3752e-01, -1.8128e-02,
          6.0570e-01, -1.0496e+00, -1.0697e+00,  1.2132e+00, -1.3417e+00,
         -8.6718e-01],
        [-1.4999e+00,  6.2729e-01,  6.9022e-01,  6.7370e-02, -1.2666e-01,
         -1.3095e+00, -1.0118e+00, -3.0987e-01,  5.2759e-01, -1.2063e-01,
          3.2312e-01, -8.2595e-01,  3.3562e-01, -2.2264e-01,  8.9543e-01,
          2.6613e-01],
        [-3.4342e-02, -3.1093e-01,  1.0125e+00, -2.3755e-01,  1.5867e+00,
         -8.4387e-01, -2.0953e+00, -1.1861e+00, -7.8347e-01,  1.9101e+00,
          1.7003e+00, -1.1138e+00,  1.2491e+00,  3.4477e-01, -9.9348e-01,
          9.9344e-01],
        [-4.0308e-01, -1.4616e+00,  1.4168e-01, -8.5300e-01,  4.8266e-01,
         -5.8066e-01, -2.6581e-01,  1.0410e-01, -7.7254e-01, -8.0033e-02,
          1.4227e+00,  1.1910e-01,  5.0262e-01, -2.3415e-02,  1.4199e-01,
         -5.6076e-01],
        [ 7.2551e-01

In [37]:
q[:,0].shape

torch.Size([32])

In [33]:
blq = torch.split(q, 2, dim=-1)
blq

(tensor([[ 0.6838, -0.0126],
         [ 0.1048, -0.8242],
         [-0.7673, -0.3724],
         [-1.3736,  0.4874],
         [-1.3091, -0.8588],
         [-0.2815,  1.7733]]),
 tensor([[-0.4933, -0.3645],
         [-0.3040,  0.7227],
         [-0.2654, -0.9637],
         [ 1.6446, -0.3652],
         [-1.7364, -2.4028],
         [ 0.0362, -0.0362]]),
 tensor([[ 0.1781, -0.1061],
         [ 0.5120,  0.5892],
         [-1.3006,  0.8669],
         [ 0.9069,  1.0918],
         [ 1.7566,  1.5345],
         [ 0.9966, -0.1511]]),
 tensor([[-0.0952, -0.6337],
         [-0.9390,  0.6284],
         [ 0.5928,  1.7647],
         [-0.0257, -0.1415],
         [ 1.0187, -1.0913],
         [ 0.8179, -0.1588]]))

In [17]:
blq[1]

tensor([[-0.7673, -0.3724, -0.2654, -0.9637, -1.3006,  0.8669,  0.5928,  1.7647],
        [-1.3736,  0.4874,  1.6446, -0.3652,  0.9069,  1.0918, -0.0257, -0.1415]])

In [18]:
b1,b2,b3 = blq
b2

tensor([[-0.7673, -0.3724, -0.2654, -0.9637, -1.3006,  0.8669,  0.5928,  1.7647],
        [-1.3736,  0.4874,  1.6446, -0.3652,  0.9069,  1.0918, -0.0257, -0.1415]])

In [21]:
torch.empty_like(q)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
a1 = torch.ones(10)
a1

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
s = torch.randn(5,3)
s

tensor([[-0.3414,  0.6118, -1.3113],
        [-0.1699,  0.1655,  1.2959],
        [-0.0098,  0.5535,  0.1139],
        [-1.5750, -0.9086, -1.0091],
        [ 0.7497,  1.7933,  0.9144]])

In [52]:
m = torch.randn(5,3)
mij = m[:,1]
mij

tensor([ 0.6114,  1.4985, -0.1683,  0.5605, -1.5205])

In [53]:
s.shape, mij.shape

(torch.Size([5, 3]), torch.Size([5]))

In [67]:
mijj = mij[:,None]
mijj

tensor([[ 0.6114],
        [ 1.4985],
        [-0.1683],
        [ 0.5605],
        [-1.5205]])

In [68]:
mijj.squeeze()

tensor([ 0.6114,  1.4985, -0.1683,  0.5605, -1.5205])

In [65]:
mij

tensor([ 0.6114,  1.4985, -0.1683,  0.5605, -1.5205])

In [57]:
s

tensor([[-0.3414,  0.6118, -1.3113],
        [-0.1699,  0.1655,  1.2959],
        [-0.0098,  0.5535,  0.1139],
        [-1.5750, -0.9086, -1.0091],
        [ 0.7497,  1.7933,  0.9144]])

In [64]:
torch.sum(s, dim=-1)

tensor([-1.0409,  1.2915,  0.6576, -3.4927,  3.4574])

In [70]:
torch.diag(mijj.squeeze())

tensor([[ 0.6114,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  1.4985,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.1683,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.5605,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -1.5205]])

In [94]:
q = torch.randn(8,12,8)
blocksq = torch.split(q, 2, dim=-1)

In [97]:
blocksq[3].shape

torch.Size([8, 12, 2])

In [98]:
torch.arange(4,10)

tensor([4, 5, 6, 7, 8, 9])

In [117]:
Sij = torch.randn(2,3,5)
Sij

tensor([[[-0.9481,  1.0548,  1.3874,  0.0080,  0.4512],
         [ 0.2631,  0.6650, -0.5231, -1.2838, -0.4915],
         [ 0.2978, -1.3058,  1.3135,  0.9232, -0.6125]],

        [[ 0.0289,  0.1043,  0.8185,  1.4020, -0.0016],
         [-0.3065, -0.1309,  0.2347, -0.4925,  0.5462],
         [-0.2858,  0.3100,  0.7914, -0.3225, -0.4433]]])

In [120]:
maxx = torch.max(Sij, dim=-1, keepdim=True).values
maxx, maxx.shape

(tensor([[[1.3874],
          [0.6650],
          [1.3135]],
 
         [[1.4020],
          [0.5462],
          [0.7914]]]),
 torch.Size([2, 3, 1]))

In [121]:
mi = torch.randn(2, 3,1)
mi

tensor([[[ 1.8994],
         [-0.8356],
         [ 1.1658]],

        [[-0.1316],
         [-0.4116],
         [ 0.3551]]])

In [122]:
mii = torch.max(mi, maxx)

In [123]:
mii.shape

torch.Size([2, 3, 1])

In [129]:
L = torch.randn(4,12)
L

tensor([[ 1.3332, -0.2984,  2.1395,  0.6017,  0.1716,  2.4284,  0.0665,  0.8215,
         -0.0304,  0.2923,  1.2660, -2.3065],
        [-0.7603,  1.0139,  1.4268,  0.8791, -0.2469,  1.2425,  0.6510,  0.5422,
          0.5200,  1.6079, -1.4144, -1.8577],
        [ 1.8540, -0.3928,  0.7340, -1.6403, -0.6244, -0.3301, -1.0858,  0.0654,
         -0.0982,  1.3671,  0.0044, -0.4010],
        [ 0.8131,  1.4320,  0.6003, -1.0658,  0.4637, -1.6006,  0.0892,  0.2700,
         -1.1599, -0.4874,  1.0146, -0.7249]])

In [130]:
blocksL = torch.split(L, 3, dim=-1)
blocksL

(tensor([[ 1.3332, -0.2984,  2.1395],
         [-0.7603,  1.0139,  1.4268],
         [ 1.8540, -0.3928,  0.7340],
         [ 0.8131,  1.4320,  0.6003]]),
 tensor([[ 0.6017,  0.1716,  2.4284],
         [ 0.8791, -0.2469,  1.2425],
         [-1.6403, -0.6244, -0.3301],
         [-1.0658,  0.4637, -1.6006]]),
 tensor([[ 0.0665,  0.8215, -0.0304],
         [ 0.6510,  0.5422,  0.5200],
         [-1.0858,  0.0654, -0.0982],
         [ 0.0892,  0.2700, -1.1599]]),
 tensor([[ 0.2923,  1.2660, -2.3065],
         [ 1.6079, -1.4144, -1.8577],
         [ 1.3671,  0.0044, -0.4010],
         [-0.4874,  1.0146, -0.7249]]))

In [131]:
blocksL[1].shape

torch.Size([4, 3])