In [52]:
import torch
torch.randint(0, 10,(2,3)).to('mps')

tensor([[1, 1, 6],
        [6, 5, 0]], device='mps:0')

In [ ]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
Q.sum().backward()
print(a.grad_fn)


In [55]:
Q = 3*a**3 - b**2

In [58]:
Q.sum().backward()

In [64]:
print(a.grad)

tensor([36., 81.])


In [69]:
import itertools

d_model = [16, 32, 64, 128]
seq_len = [256, 1024, 4096, 8192, 16384]

# Generate and iterate through the cartesian product
for dm, seql in itertools.product(d_model, seq_len):
    print(f'dm{dm}seql{seql}')


dm16seql256
dm16seql1024
dm16seql4096
dm16seql8192
dm16seql16384
dm32seql256
dm32seql1024
dm32seql4096
dm32seql8192
dm32seql16384
dm64seql256
dm64seql1024
dm64seql4096
dm64seql8192
dm64seql16384
dm128seql256
dm128seql1024
dm128seql4096
dm128seql8192
dm128seql16384


In [76]:
from collections import defaultdict

# 1. Initialize once
aa = defaultdict(list)

In [77]:
aa['a'].append(1)

In [79]:
dict(aa)

{'a': [1]}

In [ ]:
x = torch.randn(5,10)
w = torch.randn(10)


tensor([[-0.9752, -0.3662, -0.5624, -1.3200, -1.1085,  2.5368,  0.2549, -1.0330,
         -0.8862, -0.2508],
        [ 0.4298,  0.1446, -0.5916,  0.7506, -0.0973,  0.7857, -1.9282,  0.1568,
         -0.9113,  0.3214],
        [ 0.9793,  0.7772,  0.5197, -1.3204, -0.9264,  0.5308,  0.4097, -0.3539,
          0.9132,  2.5170],
        [ 1.4555, -0.5885, -0.4251, -0.5506,  1.7127,  0.1584, -0.1262,  0.0834,
          1.2635,  0.4677],
        [-1.5229, -0.4951, -0.5981, -1.0667, -1.6461,  0.3318,  1.0025, -0.3434,
         -1.6264, -0.1491]])

In [90]:
w = torch.randn(10)
w.shape

torch.Size([10])

In [89]:
w @ x.T

tensor([ 2.4601,  2.9836, -7.9244, -5.4094,  4.0456])